persistence true
persistence_location /mosquitto/data/

log_dest file /mosquitto/log/mosquitto.log

# 1. Standard MQTT Listener (TCP)
listener 1883 0.0.0.0
protocol mqtt

# 2. WebSockets Listener (For browser-based tools)
listener 9001 0.0.0.0
protocol websockets

# Security Settings
allow_anonymous true
