
name: STM32-DB
services:
  influxdb2:
    image: influxdb:alpine
    container_name: influxdb2
    ports:
      - "8086:8086"  # InfluxDB UI and API
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=${INFLUXDB_USERNAME:-myusername}
      - DOCKER_INFLUXDB_INIT_PASSWORD=${INFLUXDB_PASSWORD:-mypassword}
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=${INFLUXDB_TOKEN:-mytoken}
      - DOCKER_INFLUXDB_INIT_ORG=IoT
      - DOCKER_INFLUXDB_INIT_BUCKET=Node-RED
      - DOCKER_INFLUXDB_INIT_RETENTION=1w
    volumes:
      - influxdb2-data:/var/lib/influxdb2
      - influxdb2-config:/etc/influxdb2
    networks:
      - iot-network
    restart: unless-stopped

volumes:
  influxdb2-data:
  influxdb2-config:

networks:
  iot-network:
    driver: bridge